dist: xenial
language: python
python:
    - "3.7"
install:
    - pip install -r requirements.txt
    - pip install coverage
    - pip install python-coveralls
script: make test
after_success:
  - coveralls
