version: "3"
services:
    evernotebot:
        image: djudman/evernote-telegram-bot:latest
        container_name: evernotebot # NOTE: If container name is specified there is only one container may exists
        ports:
            - "10.135.98.34:8000:8000"
        volumes:
            - "./logs:/srv/logs"
