debug: true
secret: secret  # TODO: put here secret key for project
host: evernotebot.djudman.info:88
storage:
    providers:
        memory:
            class: data.storage.providers.MemoryProvider
            default: true
        mongo:
            class: data.storage.providers.MongoProvider
            default: true
            connection_string: mongodb://127.0.0.1:27017/
            db: evernotebot
telegram:
    bot_url: http://telegram.me/evernoterobot
    token: secret  # TODO: put here token for your bot. You can get the token via BotFather bot in telegram.
evernote:
    oauth_path: /some/path
    access:
        token: secret
        basic:
            key: secret
            secret: secret
        full:
            key: secret
            secret: secret
admin:
    user: root  # TODO: put here your username
    password: root  # TODO: put here salted sha1 of your password
