debug: true
host: evernotebot.djudman.info:88
storage:
    providers:
        memory:
            class: data.storage.providers.MemoryProvider
        mongo:
            class: data.storage.providers.MongoProvider
            default: true
            connection_string: mongodb://127.0.0.1:27017/
            db: evernotebot
telegram:
    token: secret
evernote:
    oauth_path: /some/path
    access:
        token: secret
        basic:
            key: secret
            secret: secret
        full:
            key: secret
            secret: secret
